version: '3.4'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    
  pulumi:
    image: pulumi/pulumi
    command: up -y -s local
    working_dir: /app
    volumes:
      - .:/app
    environment:
     - PULUMI_ACCESS_TOKEN
    depends_on:
      - localstack
